### PR TITLE
Improve implementation

### PR DESCRIPTION
**Pull request by Juno-T**
This is the first pr of a few upcoming pull requests following discussion in issue #3.

This PR is only a code improvement. There is **_no functionality change_**, everything still work the same way as before. Every if condition, every mode of the prompt stay exactly the same.

## Changes
There are a lot of line changes but basicallly the changes are:
- Using `langchain` package for calling LLM (instead of `openai` package). This will make future LLMs integration easier.
- Debug the unintentionally restart of the program when running from CLI bug.
- Improve code execution in subprocess by making the function pure (allow it to use empty dict for global argument instead of the whole `globals()`). This prevents naming collision which makes the `globals()`'s name checking code unnecessary. The code will be executed completely independently from the main process.
- Introducing read-only object for code-related data called `CodeBlob`. This makes the code easier to understand and making the code shorter. It also serve as a common interface between execution module and prompting module.
- Remove unused code and format code.
- Update README

## Testing
I have tested with simple runs through cli:
```
python3 mg.py -o "a program that output some funny joke" -f "joke.py" -out "funny joke as stdout" -l 60 -t 2 -v True
```
and
```
python3 mg.py -o "Consider the function f(x)=(x^3)((4x+5)^2), for what value of x is f'(x)=0" -f "mymath.py" -out "values of x such that f'(x)=0" -e "1.sympy" -l 60
```

Both of them worked perfectly.

## Footer
My next steps if the PR pass:
- Storing code execution history, improve logging & reproducibility, save & load MetaLLM module.
- make prompting module works with prompt files (json or something).
- Explore other prompting techniques.

### CODE REVIEW

**Comment by Juno-T** [comment]
Should it be a PR for a new branch? Or main branch is ok?

**Comment by JLX0** [comment]
Thanks for your hard and excellent work, Juno! The code can be very helpful for developers. 

There is a small bug as shown in the picture below. The bug happens when the target program is buggy. Please fix the bug and let me know!
dc978ab23d7768ad448a470916641a3

**Comment by Juno-T** [comment]
I'll add unittest and then fix the bug. I'll let you know once it's finished.

**Comment by Juno-T** [comment]
I have added unit test for code execution under `test` dir. And solved the mentioned bug, tested with 2 more examples: generate neural networks and generate audio file from news.

About the branch, if you want this PR to be merged in a new branch, please create one (could be named like `development`/`dev` or `experimental`/`exp`) so that I can change the PR's target branch.

**Comment by JLX0** [comment]
Dear Juno.

Thanks for your efforts!

please merge into develop-juno

**Comment by Juno-T** [comment]
I have changed the target branch to `develop-juno`. You can merge and close the merge request.

**Pull request merged**
